### ISSUE TITLE
Access through blueprint?

### ISSUE THREAD

**Issue by gbernal** [Jin-Vyral/ZMQUE#1]
Hi @Jin-Vyral 

Thank you for sharing this project. I have a question regarding how to use your plugin. 
Is this plugin accessible through blueprint? 

Also to use it do you just copy the ZMQUE to the plugins folder?

Thank you! looking forward to your reply.

**Comment by Jin-Vyral** [comment]
On Wed, 28 Nov 2018 12:13:34 -0500, gbernal <notifications@github.com>  
wrote:

>
> Hi @Jin-Vyral
Hello! Glad to see my work may be of use to another.
>
> Thank you for sharing this project. I have a question regarding how to  
> use your plugin.
> Is this plugin accessible through blueprint?
No BP. It just goes straight-through to the ZMQ API. It just gets ZMQ into  
C++ UE4.
>
> Also to use it do you just copy the ZMQUE to the plugins folder?
I use this plugin within another plugin (which is used by Blueprints) so  
I'm not sure if you can just use it on its own. Look into "Third Party  
plugins" and hopefully you will find some answers.

Cheers,
Jin

**Comment by gbernal** [comment]
Hi Jin,
thank you for the prompt reply! Do you mind a expanding this comment

>  I use this plugin within another plugin (which is used by Blueprints) so
> I'm not sure if you can just use it on its own. 

Is the other plugin not open source? or if it is do you have an example scene with your implementation?
That would make it even easier to adopt your plugin

thanks!

**Comment by Jin-Vyral** [comment]
I can't share the other plugin. Sorry.

I think it should work in a C++ UE4 project if you create a sub-folder  
 from your project folder called "Plugins" and put my ZMQUE directory in  
there. Then in your (Project).Build.cs file, you want to add:

PrivateDependencyModuleNames.Add("ZMQUE");

You may also need to specify ZMQUE in your (Project).uproject file.

Then you can include ZMQUE.h in your source code and access the ZMQ  
functions.

Try it in a test project so you don't mess up anything important.

If you get past all that then you also need to know that you need to copy  
the ZMQ DLL into your packaged game manually.

-Jin

**Comment by gbernal** [comment]
Jin,

Thank you for sharing those pointers! I will give it a try and If I manage to get it to work, 
I will try to make an unrestricted template project.

**Comment by dhhunter** [comment]
I have been unable to get any of your instructions to work, it looks like they massively changed how plugins work in 4.21.1.  I really only need to access the ZMQ API from my C++ code, Blueprints make me want to break things; however, where they are required I can setup my C++ classes to play nice with them.  I am very new to Unreal development, it was going fairly smoothly until I had to start beating my head against the Build System and that is really giving me a headache.  Any help would be amazingly appreciated.

Thank you and have a very Blessed Day!

**Comment by dhhunter** [comment]
Okay, using the method from [https://wiki.unrealengine.com/Linking_Static_Libraries_Using_The_Build_System]() I was finally able to get ZMQUE to work!!!

Thank you so much for your hard work in making this available!

**Comment by Jin-Vyral** [comment]
I'm happy to see that you got it working. Sorry for the uber-late reply -- I've been insanely busy.
